# .github/workflows/main.yml

name: Create Merge Request

on:
  push:
    branches:
      - DEV
  workflow_dispatch: # Manual trigger event

jobs:
  create_merge_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge DEV into main
        run: |
          git checkout main
          git merge DEV --no-ff --no-commit || echo "::set-output name=merge_failed::true"
          git push origin main || echo "::set-output name=push_failed::true"

