# .github/workflows/main.yml
# This configuration is for GitHub Actions

name: Create Merge Request

on:
  push:
    branches:
      - DEV

jobs:
  create_merge_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge DEV into main
        run: |
          git checkout main
          git merge DEV --no-ff --no-commit
          git push origin main
