# .github/workflows/main.yml

name: Create Merge Request

on:
  push:
    branches:
      - DEV
  workflow_dispatch: # Manual trigger event

jobs:
  create_merge_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge DEV into main
        run: |
          git checkout main
          git merge DEV --no-ff --no-commit

          # Manual conflict resolution
          # Open the affected files in a text editor and resolve the conflicts

          # Add the resolved changes to the staging area
          git add .

          # Finalize the merge commit
          git commit

          # Push the merged changes to the remote main branch
          git push origin main
