name: Create Merge Request
on:
  push:
    branches:
      - DEV

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Merge Request
        run: |
          git checkout DEV
          git fetch origin
          git merge origin/DEV
          git push --follow-tags
          git checkout main
          git merge DEV
          git push
          # Create a merge request with the following title:
          # "Merge DEV into main"
          # and the following body:
          # "This merge request merges the DEV branch into the main branch.
          # Please review and merge."
          # You can also use the following to set the assignee and labels of your merge request:

          # Set the variables
          MR_TITLE="Merge DEV into main"
          MR_BODY="This merge request merges the DEV branch into the main branch.\nPlease review and merge."
          MR_ASSIGNEE="NavyaNelluri"
          MR_LABELS="label1,label2"

          # Create the merge request using the GitHub API
          RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "'"$MR_TITLE"'",
              "body": "'"$MR_BODY"'",
              "assignee": "'"$MR_ASSIGNEE"'",
              "labels": ["'"$MR_LABELS"'"]
            }' \
            "https://api.github.com/repos/${{ github.repository }}/pulls")

          # Extract the merge request number from the API response
          MR_NUMBER=$(echo $RESPONSE | jq -r '.number')

          echo "Merge request created: $MR_NUMBER"
