name: Create Merge Request
on:
  push:
    branches:
      - DEV

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Merge Request
        run: |
          git checkout DEV
          git fetch origin
          git merge origin/DEV
          git push --follow-tags
          git checkout main
          git merge DEV
          git push
          # Create a merge request with the following title:
          # "Merge DEV into main"
          # and the following body:
          # "This merge request merges the DEV branch into the main branch.
          # Please review and merge."
          # You can also use the following to set the assignee and labels of your merge request:
\
