name: Move code on push

on:
  push:
    branches:
      - DEV

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DEV branch
        uses: actions/checkout@v2
        with:
          ref: DEV

      - name: Move code to main branch
        run: |
          git checkout main
          git merge DEV
          git push
