name: Create Merge Request
on:
  push:
    branches:
      - dev

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Merge Request
        run: |
          git checkout dev
          git fetch origin
          git merge origin/dev
          git push --follow-tags
          git checkout master
          git merge dev
          git push
          # Create a merge request with the following title:
          # "Merge dev into master"
          # and the following body:
          # "This merge request merges the dev branch into the master branch.
          # Please review and merge."
