name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      # For example:
      - name: Print Message
        run: echo "This workflow was manually triggered."

      # Add more steps as needed
