name: App test

on:
  push:
    branches: [ main, issue_6 ]
  pull_request:
    branches: [ main, issue_6 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change directory
      run: cd #filelocation

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd #filelocation
        yarn install
    - name: Run tests
      run: |
        cd #filelocation
        yarn test
